services:
  angular:
    build: .
    image: angular-node20
    container_name: angular-dev

    working_dir: /app/frontend

    volumes:
      - ./frontend:/app/frontend

    ports:
      - "4200:4200"

    stdin_open: true
    tty: true

    environment:
      NG_CLI_ANALYTICS: "false"
      CI: "true"

    command: >
      sh -c "
      if [ ! -f package.json ]; then
        echo 'Creando proyecto Angular';
        cd /app;
        ng new frontend --routing --style=css --skip-git --defaults --interactive=false;
      fi;

      cd /app/frontend;

      npm install;

      ng serve --host 0.0.0.0 --poll=2000;
      "